#!/bin/bash

# Start script for libp2p-gossipsub-topic-debugger
# Automatically handles both development (build from source) and production (use pre-built image) modes

set -e

# Determine docker compose command
if command -v docker-compose &> /dev/null; then
    DOCKER_COMPOSE_CMD="docker-compose"
else
    DOCKER_COMPOSE_CMD="docker compose"
fi

# Check if relayer-py directory exists for building from source
RELAYER_DIR="./relayer-py"
OVERRIDE_FILE="docker-compose.override.yml"

if [ ! -d "$RELAYER_DIR" ]; then
    # Production mode: relayer-py doesn't exist, use pre-built image
    echo "📦 relayer-py directory not found - using pre-built image from registry"
    
    # Create override file to remove build section so docker-compose uses image only
    # When build context doesn't exist, docker-compose will use image
    cat > "$OVERRIDE_FILE" <<'EOF'
# Auto-generated by start.sh for production mode
# Removes build section so docker-compose uses pre-built image
services:
  relayer-py:
    build: null
EOF
    echo "✅ Created $OVERRIDE_FILE - will use pre-built image"
else
    # Development mode: relayer-py exists, build from source
    echo "🔨 relayer-py directory found - building from source"
    
    # Remove override file - when build context exists, docker-compose will build
    # Even though both image and build are in base file, build takes precedence
    if [ -f "$OVERRIDE_FILE" ]; then
        rm -f "$OVERRIDE_FILE"
        echo "✅ Removed $OVERRIDE_FILE - will build from source"
    fi
fi

# Build and start services
echo "🚀 Building and starting services..."

# CRITICAL: Always use --build flag to force building when context exists
# This ensures docker-compose builds from source instead of pulling image
# When ./relayer-py exists: docker-compose will build (build takes precedence)
# When ./relayer-py doesn't exist: docker-compose will skip build and use image
if [ -d "$RELAYER_DIR" ]; then
    # Development mode: explicitly build to ensure we use source, not pulled image
    echo "   Building all services (including relayer-py from source)..."
    $DOCKER_COMPOSE_CMD build
else
    # Production mode: build other services, relayer-py will use image
    echo "   Building other services (relayer-py will use pre-built image)..."
    $DOCKER_COMPOSE_CMD build 2>&1 | grep -v "relayer-py" || true
fi

# Start services with --build flag to ensure latest build is used
# In development mode, this uses the locally built image
# In production mode, this pulls/uses the pre-built image
$DOCKER_COMPOSE_CMD up -d --build

# Tail logs for the main container
echo "📋 Tailing logs for p2p-debugger container..."
$DOCKER_COMPOSE_CMD logs -f p2p-debugger