#!/bin/bash

# Start script for snapshot-activity-tracker-updater
# Supports operation modes: minimal, watcher, full
#
# Modes:
#   minimal - Watching only: tracker + redis (collect finalizations, save tallies)
#   watcher - Watching + dashboard: tracker + redis + dashboard-api
#   full    - Watching + on-chain + dashboard: tracker + redis + relayer + rabbitmq + dashboard-api
#
# Dashboard dev (no full rebuild): docker compose --profile watcher up -d && cd frontend && npm run dev

set -e

# Mode selection
MODE="${1:-full}"
case "$MODE" in
  full|watcher|minimal)
    echo "🚀 Starting in $MODE mode..."
    ;;
  *)
    echo "Usage: $0 [minimal|watcher|full]"
    echo "  minimal - Watching only: tracker + redis (no dashboard, no on-chain)"
    echo "  watcher - Watching + dashboard: tracker + redis + dashboard-api"
    echo "  full    - Full: tracker + redis + relayer + rabbitmq + dashboard-api"
    exit 1
    ;;
esac

# Determine docker compose command
if command -v docker-compose &> /dev/null; then
    DOCKER_COMPOSE_CMD="docker-compose"
else
    DOCKER_COMPOSE_CMD="docker compose"
fi

# Check if relayer-py directory exists for building from source
RELAYER_DIR="./relayer-py"
OVERRIDE_FILE="docker-compose.override.yml"

if [ ! -d "$RELAYER_DIR" ]; then
    # Production mode: relayer-py doesn't exist, use pre-built image
    echo "📦 relayer-py directory not found - using pre-built image from registry"
    
    # Create override file to remove build section so docker-compose uses image only
    # When build context doesn't exist, docker-compose will use image
    cat > "$OVERRIDE_FILE" <<'EOF'
# Auto-generated by start.sh for production mode
# Removes build section so docker-compose uses pre-built image
services:
  relayer-py:
    build: null
EOF
    echo "✅ Created $OVERRIDE_FILE - will use pre-built image"
else
    # Development mode: relayer-py exists, build from source
    echo "🔨 relayer-py directory found - building from source"
    
    # Remove override file - when build context exists, docker-compose will build
    # Even though both image and build are in base file, build takes precedence
    if [ -f "$OVERRIDE_FILE" ]; then
        rm -f "$OVERRIDE_FILE"
        echo "✅ Removed $OVERRIDE_FILE - will build from source"
    fi
fi

# Build docker compose profiles based on mode
COMPOSE_PROFILES=""
case "$MODE" in
  full)
    COMPOSE_PROFILES="full,watcher"
    echo "   Services: tracker, redis, relayer-py, rabbitmq, dashboard-api"
    ;;
  watcher)
    COMPOSE_PROFILES="watcher"
    echo "   Services: tracker, redis, dashboard-api"
    ;;
  minimal)
    COMPOSE_PROFILES=""
    echo "   Services: tracker, redis"
    ;;
esac

# Build only the services needed for this mode (avoids rebuilding dashboard when in minimal)
case "$MODE" in
  full)
    if [ -d "$RELAYER_DIR" ]; then
      echo "🚀 Building: tracker, dashboard-api, relayer-py"
      $DOCKER_COMPOSE_CMD build snapshot-activity-tracker dashboard-api relayer-py
    else
      echo "🚀 Building: tracker, dashboard-api (relayer-py from registry)"
      $DOCKER_COMPOSE_CMD build snapshot-activity-tracker dashboard-api
    fi
    ;;
  watcher)
    echo "🚀 Building: tracker, dashboard-api"
    $DOCKER_COMPOSE_CMD build snapshot-activity-tracker dashboard-api
    ;;
  minimal)
    echo "🚀 Building: tracker"
    $DOCKER_COMPOSE_CMD build snapshot-activity-tracker
    ;;
esac

# Start services
export COMPOSE_PROFILES
$DOCKER_COMPOSE_CMD up -d

# Tail logs for the main container
echo "📋 Tailing logs for snapshot-activity-tracker container..."
$DOCKER_COMPOSE_CMD logs -f snapshot-activity-tracker